### ISSUE TITLE
DocBuilder: GetCommentsReport and GetReviewReport require non-existing file

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/api.onlyoffice.com#24]
In DocumentBuilder examples for `GetCommentsReport` and `GetReviewReport` methods there is 
`builder.OpenFile("DocumentWithReview.docx");` and `builder.OpenFile("DocumentWithComments.docx");` lines.
This file is not found on any page of https://api.onlyoffice.com and those examples are non-functional.
Need to place link to those files somehow

**Comment by alexandervnuchkov** [comment]
Fixed: https://github.com/ONLYOFFICE/api.onlyoffice.com/commit/1460ec10b8aeac3fe43af4eed7513977d04125de
