### ISSUE TITLE
DocBuilder: more detailed example for GetDocument method

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/api.onlyoffice.com#25]
Curren example for `GetDocument` method is pretty useless:
```
var oDocument = Api.GetDocument();
```
I think there should be more detailed example (it may duplicate some other example, but at least it will do something)

**Comment by alexandervnuchkov** [comment]
Fixed: https://github.com/ONLYOFFICE/api.onlyoffice.com/commit/42b9ef0e3e6b33da0ac3c9cee13c2cf2f9b14821
