### ISSUE TITLE
CommunityServer: Different API-methods have same name

### ISSUE THREAD

**Issue by olga-nesterova** [ONLYOFFICE/api.onlyoffice.com#50]
In Community Server documentation different API-methods have same name, for exampe "Create new event" repeat 4 times (http://api.teamlab.info/portals/method/calendar/post/api/2.0/calendar/event) 
Need to make unique names for all API-methods
 ![Снимок экрана 2019-05-24 в 13 06 30](https://user-images.githubusercontent.com/40513035/58324339-481e0380-7e2f-11e9-9632-13699d52380f.png)

**Comment by Eloncase** [comment]
There is a thing called [Member Overloading](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/member-overloading), basically it allows you to have same names for functions that are doing the same opearion but differs in parameter types
